name: Nexus CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  contracts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Hardhat dependencies
        working-directory: ./contracts
        run: npm ci || npm install
      - name: Run Smart Contract Tests
        working-directory: ./contracts
        run: npx hardhat test

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci || npm install
      - name: Build Next.js
        working-directory: ./frontend
        run: npm run build
